Proyecto/Basquet2023/Basquet2023/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('Basquet2023_DatosApp/', include('Basquet2023_DatosApp.urls'))
]

Proyecto/Basquet2023/Basquet2023_DatosApp/urls.py
from django.urls import path
from Basquet2023_DatosApp import views


urlpatterns = [  
    path('inicio/', views.inicio, name='inicio'),
    path('usuario/' , views.usuario, name='usuario'),
    path('equipos/' , views.equipo, name='equipos'),
    path('registrarcuenta/', views.registrarcuenta, name='registrarcuenta'),
     ]

Proyecto/Basquet2023/Basquet2023_DatosApp/models.py
from django.db import models

class Cuenta(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    email = models.EmailField(unique=True)
    TIPOS_CUENTA = (
        ('periodista', 'Periodista'),
        ('tecnico', 'Técnico'),
        ('jugador', 'Jugador'),
        ('aficionado', 'Aficionado'),
    )
    tipo_cuenta = models.CharField(max_length=50, choices=TIPOS_CUENTA)

    def __str__(self):
        return self.email

class equipo(models.Model):
    nombre = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

Proyecto/Basquet2023/Basquet2023_DatosApp/forms.py
from django import forms
from Basquet2023_DatosApp.models import Cuenta, equipo

class RegistroCuentaForm(forms.ModelForm):
    class Meta:
        model = Cuenta
        fields = ['nombre', 'apellido', 'telefono', 'email', 'tipo_cuenta']


class equipoForm(forms.ModelForm):
    class Meta:
        model = equipo
        fields = ['nombre', 'ciudad']

Proyecto/Basquet2023/Basquet2023_DatosApp/views.py
from django.shortcuts import render, redirect
from Basquet2023_DatosApp.forms import RegistroCuentaForm, equipoForm

def inicio(request):
    return render(request, "Basquet2023_DatosApp/index.html")

def usuario(request):
    return render(request, 'Basquet2023_DatosApp/usuario.html')

def registrarcuenta(request):
    if request.method == 'POST':
        form = RegistroCuentaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('inicio')  # Redirecciona a la página de inicio después del registro exitoso
    else:
        form = RegistroCuentaForm()
    
    return render(request, 'registrarcuenta.html', {'form': form})

def equipo(request):
    if request.method == 'POST':
        form = equipoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('equipos')  # Redirecciona a la página de equipos después de guardar
    else:
        form = equipoForm()
    
    return render(request, 'equipos.html', {'form': form})

Proyecto/Basquet2023/Basquet2023_DatosApp/templates/Basquet2023_DatosApp/index.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>INDEX</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Basquet2023_DatosApp/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="#page-top">Basquet2023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'equipos' %}">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuario' %}">Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'registrarcuenta' %}">registrarcuenta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">Basquet</h1>
                    <h2 class="masthead-subheading mb-0">Blogs y Foros</h2>
                    <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Ver Mas</a>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        <!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'Basquet2023_DatosApp/assets/img/01.jpg' %}" alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">Opiniones Profesionales</h2>
                            <p>Solo Jugadores, Tecnicos y Periodistas podrán opinar en esta seccion</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Yaya2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Proyecto/Basquet2023/Basquet2023_DatosApp/templates/Basquet2023_DatosApp/registrarcuenta.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
    <title>crear Cuenta</title>
    <link href="{% static 'Basquet2023_DatosApp/css/styles.css' %}" rel="stylesheet">
    <style>
        body {
            background-color: #000;
            color: #FFF;
            font-family: Arial, sans-serif;
        }

        .container {
            text-align: center;
            margin-top: 50px;
        }

        .form-container {
            width: 400px;
            margin: 0 auto;
            background-color: #333;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }

        .form-container h2 {
            font-size: 24px;
            color: #FFA500;
            margin-bottom: 20px;
        }

        .form-container label {
            display: block;
            font-size: 16px;
            margin-bottom: 10px;
            color: #FFF;
        }

        .form-container input[type="text"],
        .form-container input[type="email"],
        .form-container select {
            width: 100px;
            padding: 8px;
            font-size: 16px;
            border-radius: 5px;
            border: 1px solid #CCC;
            margin-bottom: 20px;
        }

        .form-container select {
            height: 36px;
        }

        .form-container button[type="submit"] {
            background-color: #FFA500;
            color: #FFF;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
        }

        .form-container button[type="submit"]:hover {
            background-color: #FF8500;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="form-container">
            <h2>registrar cuenta</h2>
            <form method="POST" action="{% url 'registrarcuenta' %}">
                {% csrf_token %}
                <label for="id_nombre">Nombre:</label>
                {{ form.nombre }}
                
                <label for="id_apellido">Apellido:</label>
                {{ form.apellido }}
                
                <label for="id_telefono">Teléfono:</label>
                {{ form.telefono }}
                
                <label for="id_email">Email:</label>
                {{ form.email }}
                
                <label for="id_tipo_cuenta">Tipo de Cuenta:</label>
                {{ form.tipo_cuenta }}
                
                <button type="submit">Registrarse</button>
            </form>
        </div>
    </div>
</body>
</html>

Proyecto/Basquet2023/Basquet2023_DatosApp/templates/Basquet2023_DatosApp/usuario.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Usuario</title>
    <link href="{% static 'Basquet2023_DatosApp/css/styles.css' %}" rel="stylesheet">
    <style>
        body {
            background-color: #000;
            color: #FFF;
            font-family: Arial, sans-serif;
        }

        .container {
            text-align: center;
            margin-top: 50px;
        }

        .welcome {
            font-size: 24px;
            color: #FFA500;
            margin-bottom: 20px;
            transition: font-size 0.5s;
        }

        .welcome:hover {
            font-size: 30px;
        }

        .user-info {
            background-color: #333;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }

        .user-info h3 {
            font-size: 18px;
            color: #FFA500;
            margin-bottom: 10px;
            transition: font-size 0.5s;
        }

        .user-info h3:hover {
            font-size: 24px;
            transform: scale(1.2);
        }

        .user-info ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .user-info ul li {
            margin-bottom: 10px;
        }

        .user-info ul li strong {
            font-weight: bold;
            color: #FFF;
        }

        .user-info ul li .highlight {
            color: #FFA500;
        }

        .user-info ul li:hover {
            background-color: #FFA500;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2 class="welcome">Bienvenido {{ username }}</h2>
        <div class="user-info">
            <h3>Tu información de usuario:</h3>
            <ul>
                <li><strong>Nombre:</strong> <span class="highlight">{{ nombre }}</span></li>
                <li><strong>Apellido:</strong> <span class="highlight">{{ apellido }}</span></li>
                <li><strong>Email:</strong> <span class="highlight">{{ email }}</span></li>
                <li><strong>Teléfono:</strong> <span class="highlight">{{ telefono }}</span></li>
                <li><strong>Tipo de cuenta:</strong> <span class="highlight">{{ tipo_cuenta }}</span></li>
            </ul>
        </div>
    </div>
</body>
</html>